import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Box, Flex, Stack, Grid, Wrap, AspectRatio, SimpleGrid, Heading } from "@chakra-ui/layout"
import { useMediaQuery } from '@chakra-ui/react'
import OakdaleHeader from '../components/header'
// import schoolPic from '../public/Rectangle 57.png'


export default function Home() {
    const [isLargerThan700] = useMediaQuery("(max-width: 700px)");

    return (
        <div className={styles.container}>
            <Head>
                <title>Oakdale High Esports</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/mustanglogo.webp" />
            </Head>

            <main className={styles.main}>
                <OakdaleHeader />

                <SimpleGrid columns={2} spacing={20} color="white">
                    <Box>
                        <h1>About Oakdale High<br></br>School Esports</h1>
                        <p>Fake text regarding about oakdale high school esports</p>
                        <p>Header artwork by OHS teacher Matt McDonald</p>
                    </Box>
                    <Box>
                        <img src="OHS.png" width="369px" height="198.75" alt="OHS Artwork" />
                    </Box>

                    <Box marginTop="40px">
                        <img src="Esports1.png" width="369px" height="198.75" style={{ borderRadius: "10px" }} alt="Black and white image of child at computer gaming." />
                    </Box>
                    <Box marginTop="40px">
                        <h1>About Esports</h1>
                        <p>Fake text regarding about general esports</p>
                    </Box>
                </SimpleGrid>



            </main>

            {/* Put form in footer */}
            <footer className={styles.footer}>
                <form className={styles.formFooter} action="https://gmail.us6.list-manage.com/subscribe/post?u=6c7b84c6fd110f0881bc19736&amp;id=802f764a2e" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                    <input className={styles.formInput} class="required email" id="mce-EMAIL" type="email" id="email" name="email" placeholder="EMAIL" />
                    <button className={styles.submitBtn} type="submit" id="mc-embedded-subscribe">Stay In the Loop</button>
                </form>
            </footer>
        </div >
    )
}
