import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Oakdale High Esports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.bars}></div>
        <h1 className={styles.title}>
          Oakdale High<br></br><span className={styles.accentText}>Esports</span>
        </h1>

        <div className={styles.specialText}>
          <p>Coming Soon</p>
        </div>
      </main>

      {/* Put form in footer */}
      <footer className={styles.footer}>
        <form style={{ display: "inline" }}>
          <input className={styles.formInput} type="email" id="email" name="email" placeholder="EMAIL" />
          <button className={styles.submitBtn} type="submit">Stay In the Loop</button>
        </form>
      </footer>
    </div>
  )
}
